import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'de' | 'es' | 'fr' | 'it' | 'pt';

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: Translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.investments': 'Investments',
    'nav.crypto': 'Cryptocurrencies',
    'nav.realestate': 'Real Estate',
    'nav.oilgas': 'Oil and Gas',
    'nav.nft': 'NFT',
    'nav.retirement': 'Retirement',
    'nav.loan': 'Loan',
    'nav.company': 'Company',
    'nav.dashboard': 'Dashboard',
    'nav.deposit': 'Deposit',
    'nav.withdraw': 'Withdraw',
    'nav.investments.menu': 'Investments',
    'nav.plans': 'Investment Plans',
    'nav.transactions': 'Transactions',
    'nav.kyc': 'KYC',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    // Hero Section
    'hero.badge': 'Trusted by 50,000+ investors worldwide',
    'hero.title.part1': 'Smarter investors are here.',
    'hero.title.part2': 'You should be here, too.',
    'hero.subtitle': 'Our professionals and industry-leading tools are united to do one thing: make you a smarter, more profitable investor.',
    'hero.btn.openAccount': 'Open a Free Account',
    'hero.btn.login': 'Login to Your Account',
    'hero.stats.aum': 'Assets Under Management',
    'hero.stats.investors': 'Active Investors',
    'hero.stats.experience': 'Years Experience',
    // About Section
    'about.title': 'About',
    'about.titleHighlight': 'Whitestones Markets',
    'about.description': 'Whitestones Markets is a leading global investment platform that combines cutting-edge technology with expert financial guidance. We empower investors worldwide to make smarter decisions and achieve their financial goals through diversified investment opportunities.',
    'about.secure.title': 'Secure Platform',
    'about.secure.desc': 'Bank-level security with advanced encryption protecting your investments 24/7',
    'about.award.title': 'Award Winning',
    'about.award.desc': 'Recognized globally for excellence in financial services and innovation',
    'about.expert.title': 'Expert Team',
    'about.expert.desc': 'Professional advisors with decades of combined experience in global markets',
    'about.results.title': 'Proven Results',
    'about.results.desc': 'Consistent returns and satisfied investors across multiple asset classes',
    // Investment Plans Section
    'investmentPlans.title': 'Choose Your',
    'investmentPlans.titleHighlight': 'Investment Plan',
    'investmentPlans.subtitle': 'Select the plan that best fits your investment goals and start earning today',
    'investmentPlans.totalROI': 'Total ROI',
    'investmentPlans.unlimited': 'Unlimited',
    'investmentPlans.duration': 'Duration',
    'investmentPlans.getStarted': 'Get Started',
    'investmentPlans.loading': 'Loading plans...',
    // CTA
    'cta.openAccount': 'Open a Free Account',
    'cta.login': 'Login',
    // Auth
    'auth.signup': 'Create an Account',
    'auth.login': 'Login into Account',
    'auth.fullName': 'Full Name',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.phone': 'Phone Number',
    'auth.dob': 'Date of Birth',
    'auth.country': 'Country',
    'auth.terms': 'I agree to the Terms & Conditions',
    'auth.haveAccount': 'Already have an account?',
    'auth.noAccount': 'New on our platform?',
    'auth.signInInstead': 'Sign in instead',
    'auth.createAccount': 'Create an account',
    'auth.rememberMe': 'Remember Me',
    'auth.forgotCode': 'Forgot Code?',
    'auth.submit': 'Submit',
    'auth.loading': 'Loading...',
    'auth.error': 'Error',
    'auth.success': 'Success',
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Welcome back',
    'dashboard.mainBalance': 'Main Wallet Balance',
    'dashboard.investmentBalance': 'Investment Wallet Balance',
    'dashboard.totalInvested': 'Total Invested',
    'dashboard.expectedProfit': 'Expected Profit',
    'dashboard.availableToWithdraw': 'Available to Withdraw',
    'dashboard.transferFunds': 'Transfer Funds',
    'dashboard.from': 'From',
    'dashboard.to': 'To',
    'dashboard.amount': 'Amount',
    'dashboard.submit': 'Submit Transfer',
    // Deposit
    'deposit.title': 'Deposit Funds',
    'deposit.subtitle': 'Fund your account to start investing',
    'deposit.bitcoinAddress': 'Bitcoin Deposit Address',
    'deposit.bitcoinAddressDesc': 'Send Bitcoin to this address',
    'deposit.address': 'Bitcoin Address',
    'deposit.submitProof': 'Submit Deposit Proof',
    'deposit.submitProofDesc': 'Upload proof of payment after transfer',
    'deposit.amountLabel': 'Amount (USD)',
    'deposit.proof': 'Payment Proof (Screenshot/Receipt)',
    'deposit.submit': 'Submit Deposit Request',
    'deposit.submitting': 'Submitting...',
    'deposit.requestSubmitted': 'Deposit Request Submitted',
    'deposit.requestPending': 'Your deposit is pending admin approval.',
    // Withdraw
    'withdraw.title': 'Withdraw Funds',
    'withdraw.subtitle': 'Request a withdrawal from your account',
    'withdraw.noBalance': 'No balance available',
    'withdraw.addAccount': 'Add Withdrawal Account',
    'withdraw.selectAccount': 'Select Withdrawal Account',
    'withdraw.amount': 'Withdrawal Amount',
    'withdraw.min': 'Minimum',
    'withdraw.availableBalance': 'Available Balance',
    'withdraw.submit': 'Request Withdrawal',
    'withdraw.withdrawalRequested': 'Withdrawal Requested',
    'withdraw.withdrawalPending': 'Your withdrawal is pending admin approval.',
    // Investments
    'investments.title': 'My Investments',
    'investments.subtitle': 'Track and manage your investments',
    'investments.amountInvested': 'Amount Invested',
    'investments.expectedProfit': 'Expected Profit',
    'investments.maturityDate': 'Maturity Date',
    'investments.status': 'Status',
    'investments.active': 'Active',
    'investments.completed': 'Completed',
    'investments.claimProfits': 'Claim Profits',
    'investments.timeRemaining': 'Time Remaining',
    'investments.completed.message': 'Your investment has matured! Claim your profits now by clicking the button below.',
    'investments.noInvestments': 'No active investments. Start investing today!',
    // Plans
    'plans.title': 'Investment Plans',
    'plans.subtitle': 'Choose an investment plan that suits your goals',
    'plans.minimumInvestment': 'Minimum Investment',
    'plans.expectedReturn': 'Expected Return',
    'plans.duration': 'Duration',
    'plans.invest': 'Invest Now',
    'plans.kyc.required': 'KYC verification is required before you can create investments.',
    'plans.balance.insufficient': 'Insufficient balance. You have',
    'plans.balance.available': 'available',
    'plans.investmentStarted': 'Investment Started',
    'plans.investmentCreated': 'Your investment has been created successfully.',
    // KYC
    'kyc.title': 'Know Your Customer (KYC)',
    'kyc.subtitle': 'Complete your KYC verification to unlock all features',
    'kyc.status': 'KYC Status',
    'kyc.approved': 'Approved',
    'kyc.pending': 'Pending',
    'kyc.rejected': 'Rejected',
    'kyc.rejected.reason': 'Rejection Reason',
    'kyc.personalInfo': 'Personal Information',
    'kyc.documentVerification': 'Document Verification',
    'kyc.addressVerification': 'Address Verification',
    'kyc.uploadDocument': 'Upload Document',
    'kyc.selectDocumentType': 'Select Document Type',
    'kyc.frontSide': 'Front Side',
    'kyc.backSide': 'Back Side',
    'kyc.submit': 'Submit KYC Application',
    'kyc.submitted': 'KYC Submitted',
    'kyc.submittedMessage': 'Your KYC application has been submitted. We will review it shortly.',
    'kyc.awaitingApproval': 'Awaiting Approval',
    'kyc.approved.bonus': 'Your KYC has been approved! A bonus has been credited to your account.',
    // Transactions
    'transactions.title': 'Transaction History',
    'transactions.subtitle': 'View all your account transactions',
    'transactions.date': 'Date',
    'transactions.type': 'Type',
    'transactions.amount': 'Amount',
    'transactions.status': 'Status',
    'transactions.pending': 'Pending',
    'transactions.completed': 'Completed',
    'transactions.failed': 'Failed',
    'transactions.notFound': 'No transactions found',
    // Profile
    'profile.title': 'My Profile',
    'profile.subtitle': 'Manage your personal information',
    'profile.personalDetails': 'Personal Details',
    'profile.updateProfile': 'Update Profile',
    'profile.changePassword': 'Change Password',
    'profile.currentPassword': 'Current Password',
    'profile.newPassword': 'New Password',
    'profile.confirmNewPassword': 'Confirm New Password',
    'profile.updatePassword': 'Update Password',
    // Admin Dashboard
    'admin.dashboard': 'Admin Dashboard',
    'admin.totalUsers': 'Total Users',
    'admin.pendingKYC': 'Pending KYC',
    'admin.verifiedUsers': 'Verified Users',
    'admin.totalDeposits': 'Total Deposits',
    'admin.totalWithdrawals': 'Total Withdrawals',
    'admin.activeInvestments': 'Active Investments',
    'admin.pendingDeposits': 'Pending Deposits',
    'admin.pendingWithdrawals': 'Pending Withdrawals',
    'admin.viewDetails': 'View Details',
    'admin.settings': 'Settings',
    'admin.settingsTitle': 'Website Settings',
    'admin.settingsSubtitle': 'Manage website configuration',
    'admin.depositInfo': 'Deposit Information',
    'admin.bitcoinAddress': 'Bitcoin Deposit Address',
    'admin.bitcoinQRCode': 'Bitcoin QR Code',
    'admin.uploadQRCode': 'Upload QR Code Image',
    'admin.companyInfo': 'Company Information',
    'admin.companyAddress': 'Company Address',
    'admin.companyPhone': 'Company Phone',
    'admin.companyEmail': 'Company Email',
    'admin.save': 'Save Settings',
    'admin.saved': 'Settings saved successfully',
    'admin.users': 'Users',
    'admin.deposits': 'Deposits',
    'admin.withdrawals': 'Withdrawals',
    'admin.kyc': 'KYC Management',
    'admin.approveKYC': 'Approve KYC',
    'admin.rejectKYC': 'Reject KYC',
    'admin.approveDeposit': 'Approve Deposit',
    'admin.rejectDeposit': 'Reject Deposit',
    'admin.approveWithdrawal': 'Approve Withdrawal',
    'admin.rejectWithdrawal': 'Reject Withdrawal',
    // Pages
    'page.termsTitle': 'Terms & Conditions',
    'page.privacyTitle': 'Privacy Policy',
    'page.aboutUs': 'About Us',
    'page.contactUs': 'Contact Us',
    'page.howToJoin': 'How to Join',
    // Footer
    'footer.tagline': 'Your trusted partner in building wealth through smart investments',
    'footer.contact': 'Contact',
    'footer.quickLinks': 'Quick Links',
    'footer.about': 'About Us',
    'footer.investmentOptions': 'Investment Options',
    'footer.openAccount': 'Open Account',
    'footer.login': 'Login',
    'footer.legal': 'Legal',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.termsConditions': 'Terms & Conditions',
    'footer.riskDisclosure': 'Risk Disclosure',
    'footer.compliance': 'Compliance',
    'footer.allRights': 'All rights reserved.',
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.confirm': 'Confirm',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.language': 'Language',
    'common.theme': 'Theme',
    'common.currency': 'Currency',
  },
  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.investments': 'Investitionen',
    'nav.crypto': 'Kryptowährungen',
    'nav.realestate': 'Immobilien',
    'nav.oilgas': 'Öl und Gas',
    'nav.nft': 'NFT',
    'nav.retirement': 'Altersvorsorge',
    'nav.loan': 'Darlehen',
    'nav.company': 'Unternehmen',
    'nav.dashboard': 'Dashboard',
    'nav.deposit': 'Einzahlung',
    'nav.withdraw': 'Auszahlung',
    'nav.investments.menu': 'Investitionen',
    'nav.plans': 'Investitionspläne',
    'nav.transactions': 'Transaktionen',
    'nav.kyc': 'KYC',
    'nav.profile': 'Profil',
    'nav.settings': 'Einstellungen',
    'nav.logout': 'Abmelden',
    // Hero Section
    'hero.badge': 'Vertraut von über 50.000 Investoren weltweit',
    'hero.title.part1': 'Klügere Investoren sind hier.',
    'hero.title.part2': 'Sie sollten auch hier sein.',
    'hero.subtitle': 'Unsere Fachleute und branchenführenden Tools vereinen sich für ein Ziel: Sie zu einem klügeren, profitableren Investor zu machen.',
    'hero.btn.openAccount': 'Kostenloses Konto eröffnen',
    'hero.btn.login': 'Zu Ihrem Konto anmelden',
    'hero.stats.aum': 'Verwaltetes Vermögen',
    'hero.stats.investors': 'Aktive Investoren',
    'hero.stats.experience': 'Jahre Erfahrung',
    // About Section
    'about.title': 'Über',
    'about.titleHighlight': 'Whitestones Markets',
    'about.description': 'Whitestones Markets ist eine führende globale Investmentplattform, die modernste Technologie mit fachkundiger Finanzberatung kombiniert. Wir befähigen Investoren weltweit, klügere Entscheidungen zu treffen und ihre finanziellen Ziele durch diversifizierte Investmentmöglichkeiten zu erreichen.',
    'about.secure.title': 'Sichere Plattform',
    'about.secure.desc': 'Bankebene Sicherheit mit fortschrittlicher Verschlüsselung zum Schutz Ihrer Investitionen 24/7',
    'about.award.title': 'Preisgekrönt',
    'about.award.desc': 'Weltweit anerkannt für Exzellenz in Finanzdienstleistungen und Innovation',
    'about.expert.title': 'Expertenteam',
    'about.expert.desc': 'Professionelle Berater mit jahrzehntelanger kombinierter Erfahrung in globalen Märkten',
    'about.results.title': 'Bewährte Ergebnisse',
    'about.results.desc': 'Konsistente Renditen und zufriedene Investoren in mehreren Anlageklassen',
    // Investment Plans Section
    'investmentPlans.title': 'Wählen Sie Ihren',
    'investmentPlans.titleHighlight': 'Investitionsplan',
    'investmentPlans.subtitle': 'Wählen Sie den Plan, der am besten zu Ihren Investitionszielen passt und beginnen Sie heute zu verdienen',
    'investmentPlans.totalROI': 'Gesamter ROI',
    'investmentPlans.unlimited': 'Unbegrenzt',
    'investmentPlans.duration': 'Dauer',
    'investmentPlans.getStarted': 'Loslegen',
    'investmentPlans.loading': 'Pläne werden geladen...',
    // CTA
    'cta.openAccount': 'Kostenloses Konto eröffnen',
    'cta.login': 'Anmelden',
    // Auth
    'auth.signup': 'Konto erstellen',
    'auth.login': 'In Konto einloggen',
    'auth.fullName': 'Vollständiger Name',
    'auth.email': 'E-Mail-Adresse',
    'auth.password': 'Passwort',
    'auth.confirmPassword': 'Passwort bestätigen',
    'auth.phone': 'Telefonnummer',
    'auth.dob': 'Geburtsdatum',
    'auth.country': 'Land',
    'auth.terms': 'Ich stimme den Allgemeinen Geschäftsbedingungen zu',
    'auth.haveAccount': 'Haben Sie bereits ein Konto?',
    'auth.noAccount': 'Neu auf unserer Plattform?',
    'auth.signInInstead': 'Stattdessen anmelden',
    'auth.createAccount': 'Konto erstellen',
    'auth.rememberMe': 'Angemeldet bleiben',
    'auth.forgotCode': 'Code vergessen?',
    'auth.submit': 'Absenden',
    'auth.loading': 'Wird geladen...',
    'auth.error': 'Fehler',
    'auth.success': 'Erfolg',
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.welcome': 'Willkommen zurück',
    'dashboard.mainBalance': 'Hauptwallet-Saldo',
    'dashboard.investmentBalance': 'Investitions-Wallet-Saldo',
    'dashboard.totalInvested': 'Gesamtinvestitionen',
    'dashboard.expectedProfit': 'Erwarteter Gewinn',
    'dashboard.availableToWithdraw': 'Verfügbar zum Abheben',
    'dashboard.transferFunds': 'Geld transferieren',
    'dashboard.from': 'Von',
    'dashboard.to': 'Zu',
    'dashboard.amount': 'Betrag',
    'dashboard.submit': 'Transfer absenden',
    // Deposit
    'deposit.title': 'Gelder einzahlen',
    'deposit.subtitle': 'Finanzieren Sie Ihr Konto, um mit der Investition zu beginnen',
    'deposit.bitcoinAddress': 'Bitcoin-Einzahlungsadresse',
    'deposit.bitcoinAddressDesc': 'Bitcoin an diese Adresse senden',
    'deposit.address': 'Bitcoin-Adresse',
    'deposit.submitProof': 'Einzahlungsnachweis einreichen',
    'deposit.submitProofDesc': 'Zahlungsbeleg nach Transfer hochladen',
    'deposit.amountLabel': 'Betrag (USD)',
    'deposit.proof': 'Zahlungsnachweis (Screenshot/Quittung)',
    'deposit.submit': 'Einzahlungsanfrage absenden',
    'deposit.submitting': 'Wird eingereicht...',
    'deposit.requestSubmitted': 'Einzahlungsanfrage eingereicht',
    'deposit.requestPending': 'Ihre Einzahlung wartet auf die Genehmigung durch den Admin.',
    // Withdraw
    'withdraw.title': 'Geld abheben',
    'withdraw.subtitle': 'Fordern Sie eine Auszahlung von Ihrem Konto an',
    'withdraw.noBalance': 'Kein Guthaben verfügbar',
    'withdraw.addAccount': 'Abhebungskonto hinzufügen',
    'withdraw.selectAccount': 'Abhebungskonto wählen',
    'withdraw.amount': 'Auszahlungsbetrag',
    'withdraw.min': 'Mindestbetrag',
    'withdraw.availableBalance': 'Verfügbarer Saldo',
    'withdraw.submit': 'Auszahlung anfordern',
    'withdraw.withdrawalRequested': 'Auszahlung angefordert',
    'withdraw.withdrawalPending': 'Ihre Auszahlung wartet auf die Genehmigung durch den Admin.',
    // Investments
    'investments.title': 'Meine Investitionen',
    'investments.subtitle': 'Verfolgen und verwalten Sie Ihre Investitionen',
    'investments.amountInvested': 'Investierter Betrag',
    'investments.expectedProfit': 'Erwarteter Gewinn',
    'investments.maturityDate': 'Fälligkeitsdatum',
    'investments.status': 'Status',
    'investments.active': 'Aktiv',
    'investments.completed': 'Abgeschlossen',
    'investments.claimProfits': 'Gewinne einfordern',
    'investments.timeRemaining': 'Verbleibende Zeit',
    'investments.completed.message': 'Ihre Investition ist fällig! Fordern Sie jetzt Ihre Gewinne an, indem Sie auf die Schaltfläche unten klicken.',
    'investments.noInvestments': 'Keine aktiven Investitionen. Beginnen Sie heute mit der Investition!',
    // Plans
    'plans.title': 'Investitionspläne',
    'plans.subtitle': 'Wählen Sie einen Investitionsplan, der zu Ihren Zielen passt',
    'plans.minimumInvestment': 'Mindestinvestition',
    'plans.expectedReturn': 'Erwartete Rendite',
    'plans.duration': 'Dauer',
    'plans.invest': 'Jetzt investieren',
    'plans.kyc.required': 'KYC-Verifizierung ist erforderlich, bevor Sie Investitionen erstellen können.',
    'plans.balance.insufficient': 'Unzureichender Saldo. Sie haben',
    'plans.balance.available': 'verfügbar',
    'plans.investmentStarted': 'Investition gestartet',
    'plans.investmentCreated': 'Ihre Investition wurde erfolgreich erstellt.',
    // KYC
    'kyc.title': 'Know Your Customer (KYC)',
    'kyc.subtitle': 'Führen Sie Ihre KYC-Verifizierung durch, um alle Funktionen freizuschalten',
    'kyc.status': 'KYC-Status',
    'kyc.approved': 'Genehmigt',
    'kyc.pending': 'Ausstehend',
    'kyc.rejected': 'Abgelehnt',
    'kyc.rejected.reason': 'Ablehnungsgrund',
    'kyc.personalInfo': 'Persönliche Informationen',
    'kyc.documentVerification': 'Dokumentüberprüfung',
    'kyc.addressVerification': 'Adressverifizierung',
    'kyc.uploadDocument': 'Dokument hochladen',
    'kyc.selectDocumentType': 'Dokumenttyp wählen',
    'kyc.frontSide': 'Vorderseite',
    'kyc.backSide': 'Rückseite',
    'kyc.submit': 'KYC-Bewerbung absenden',
    'kyc.submitted': 'KYC eingereicht',
    'kyc.submittedMessage': 'Ihre KYC-Bewerbung wurde eingereicht. Wir werden sie in Kürze überprüfen.',
    'kyc.awaitingApproval': 'Warten auf Genehmigung',
    'kyc.approved.bonus': 'Ihre KYC wurde genehmigt! Ein Bonus wurde auf Ihr Konto gutgeschrieben.',
    // Transactions
    'transactions.title': 'Transaktionsverlauf',
    'transactions.subtitle': 'Alle Ihre Kontotransaktionen anzeigen',
    'transactions.date': 'Datum',
    'transactions.type': 'Typ',
    'transactions.amount': 'Betrag',
    'transactions.status': 'Status',
    'transactions.pending': 'Ausstehend',
    'transactions.completed': 'Abgeschlossen',
    'transactions.failed': 'Fehlgeschlagen',
    'transactions.notFound': 'Keine Transaktionen gefunden',
    // Profile
    'profile.title': 'Mein Profil',
    'profile.subtitle': 'Verwalten Sie Ihre persönlichen Daten',
    'profile.personalDetails': 'Persönliche Daten',
    'profile.updateProfile': 'Profil aktualisieren',
    'profile.changePassword': 'Passwort ändern',
    'profile.currentPassword': 'Aktuelles Passwort',
    'profile.newPassword': 'Neues Passwort',
    'profile.confirmNewPassword': 'Neues Passwort bestätigen',
    'profile.updatePassword': 'Passwort aktualisieren',
    // Admin Dashboard
    'admin.dashboard': 'Admin-Dashboard',
    'admin.totalUsers': 'Gesamtbenutzer',
    'admin.pendingKYC': 'Ausstehend KYC',
    'admin.verifiedUsers': 'Verifizierte Benutzer',
    'admin.totalDeposits': 'Gesamteinzahlungen',
    'admin.totalWithdrawals': 'Gesamtauszahlungen',
    'admin.activeInvestments': 'Aktive Investitionen',
    'admin.pendingDeposits': 'Ausstehende Einzahlungen',
    'admin.pendingWithdrawals': 'Ausstehende Auszahlungen',
    'admin.viewDetails': 'Details anzeigen',
    'admin.settings': 'Einstellungen',
    'admin.settingsTitle': 'Website-Einstellungen',
    'admin.settingsSubtitle': 'Verwalten Sie die Website-Konfiguration',
    'admin.depositInfo': 'Einzahlungsinformationen',
    'admin.bitcoinAddress': 'Bitcoin-Einzahlungsadresse',
    'admin.bitcoinQRCode': 'Bitcoin-QR-Code',
    'admin.uploadQRCode': 'QR-Code-Bild hochladen',
    'admin.companyInfo': 'Unternehmensinformationen',
    'admin.companyAddress': 'Unternehmensadresse',
    'admin.companyPhone': 'Unternehmenstelefon',
    'admin.companyEmail': 'Unternehmens-E-Mail',
    'admin.save': 'Einstellungen speichern',
    'admin.saved': 'Einstellungen erfolgreich gespeichert',
    'admin.users': 'Benutzer',
    'admin.deposits': 'Einzahlungen',
    'admin.withdrawals': 'Auszahlungen',
    'admin.kyc': 'KYC-Verwaltung',
    'admin.approveKYC': 'KYC genehmigen',
    'admin.rejectKYC': 'KYC ablehnen',
    'admin.approveDeposit': 'Einzahlung genehmigen',
    'admin.rejectDeposit': 'Einzahlung ablehnen',
    'admin.approveWithdrawal': 'Auszahlung genehmigen',
    'admin.rejectWithdrawal': 'Auszahlung ablehnen',
    // Pages
    'page.termsTitle': 'Allgemeine Geschäftsbedingungen',
    'page.privacyTitle': 'Datenschutzrichtlinie',
    'page.aboutUs': 'Über uns',
    'page.contactUs': 'Kontaktiere uns',
    'page.howToJoin': 'Wie man beitritt',
    // Footer
    'footer.tagline': 'Ihr vertrauenswürdiger Partner beim Vermögensaufbau durch intelligente Investitionen',
    'footer.contact': 'Kontakt',
    'footer.quickLinks': 'Schnelle Links',
    'footer.about': 'Über uns',
    'footer.investmentOptions': 'Investitionsmöglichkeiten',
    'footer.openAccount': 'Konto eröffnen',
    'footer.login': 'Anmelden',
    'footer.legal': 'Rechtliches',
    'footer.privacyPolicy': 'Datenschutzrichtlinie',
    'footer.termsConditions': 'Allgemeine Geschäftsbedingungen',
    'footer.riskDisclosure': 'Risikooffenlegung',
    'footer.compliance': 'Compliance',
    'footer.allRights': 'Alle Rechte vorbehalten.',
    // Common
    'common.loading': 'Wird geladen...',
    'common.error': 'Fehler',
    'common.success': 'Erfolg',
    'common.confirm': 'Bestätigen',
    'common.cancel': 'Abbrechen',
    'common.save': 'Speichern',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.back': 'Zurück',
    'common.next': 'Nächster',
    'common.previous': 'Vorherig',
    'common.search': 'Suche',
    'common.filter': 'Filter',
    'common.export': 'Exportieren',
    'common.download': 'Herunterladen',
    'common.upload': 'Hochladen',
    'common.language': 'Sprache',
    'common.theme': 'Thema',
    'common.currency': 'Währung',
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.investments': 'Inversiones',
    'nav.crypto': 'Criptomonedas',
    'nav.realestate': 'Bienes Raíces',
    'nav.oilgas': 'Petróleo y Gas',
    'nav.nft': 'NFT',
    'nav.retirement': 'Jubilación',
    'nav.loan': 'Préstamo',
    'nav.company': 'Empresa',
    'nav.dashboard': 'Panel de Control',
    'nav.deposit': 'Depósito',
    'nav.withdraw': 'Retiro',
    'nav.investments.menu': 'Inversiones',
    'nav.plans': 'Planes de Inversión',
    'nav.transactions': 'Transacciones',
    'nav.kyc': 'KYC',
    'nav.profile': 'Perfil',
    'nav.settings': 'Configuración',
    'nav.logout': 'Cerrar Sesión',
    // Hero Section
    'hero.badge': 'Confiado por más de 50,000 inversores en todo el mundo',
    'hero.title.part1': 'Los inversores más inteligentes están aquí.',
    'hero.title.part2': 'Tú también deberías estar aquí.',
    'hero.subtitle': 'Nuestros profesionales y herramientas líderes en la industria se unen para hacer una cosa: convertirte en un inversor más inteligente y rentable.',
    'hero.btn.openAccount': 'Abrir una Cuenta Gratuita',
    'hero.btn.login': 'Iniciar Sesión en tu Cuenta',
    'hero.stats.aum': 'Activos Bajo Gestión',
    'hero.stats.investors': 'Inversores Activos',
    'hero.stats.experience': 'Años de Experiencia',
    // About Section
    'about.title': 'Acerca de',
    'about.titleHighlight': 'Whitestones Markets',
    'about.description': 'Whitestones Markets es una plataforma de inversión global líder que combina tecnología de vanguardia con orientación financiera experta. Empoderamos a inversores de todo el mundo para tomar decisiones más inteligentes y alcanzar sus objetivos financieros a través de oportunidades de inversión diversificadas.',
    'about.secure.title': 'Plataforma Segura',
    'about.secure.desc': 'Seguridad de nivel bancario con cifrado avanzado protegiendo sus inversiones 24/7',
    'about.award.title': 'Galardonado',
    'about.award.desc': 'Reconocido globalmente por excelencia en servicios financieros e innovación',
    'about.expert.title': 'Equipo Experto',
    'about.expert.desc': 'Asesores profesionales con décadas de experiencia combinada en mercados globales',
    'about.results.title': 'Resultados Probados',
    'about.results.desc': 'Rendimientos consistentes e inversores satisfechos en múltiples clases de activos',
    // Investment Plans Section
    'investmentPlans.title': 'Elija su',
    'investmentPlans.titleHighlight': 'Plan de Inversión',
    'investmentPlans.subtitle': 'Seleccione el plan que mejor se adapte a sus objetivos de inversión y comience a ganar hoy',
    'investmentPlans.totalROI': 'ROI Total',
    'investmentPlans.unlimited': 'Ilimitado',
    'investmentPlans.duration': 'Duración',
    'investmentPlans.getStarted': 'Comenzar',
    'investmentPlans.loading': 'Cargando planes...',
    // CTA
    'cta.openAccount': 'Abrir una Cuenta Gratuita',
    'cta.login': 'Iniciar Sesión',
    // Auth
    'auth.signup': 'Crear una Cuenta',
    'auth.login': 'Iniciar Sesión en la Cuenta',
    'auth.fullName': 'Nombre Completo',
    'auth.email': 'Dirección de Correo Electrónico',
    'auth.password': 'Contraseña',
    'auth.confirmPassword': 'Confirmar Contraseña',
    'auth.phone': 'Número de Teléfono',
    'auth.dob': 'Fecha de Nacimiento',
    'auth.country': 'País',
    'auth.terms': 'Acepto los Términos y Condiciones',
    'auth.haveAccount': '¿Ya tienes una cuenta?',
    'auth.noAccount': '¿Nuevo en nuestra plataforma?',
    'auth.signInInstead': 'Inicia sesión en su lugar',
    'auth.createAccount': 'Crear una cuenta',
    'auth.rememberMe': 'Recuérdame',
    'auth.forgotCode': '¿Olvidaste el código?',
    'auth.submit': 'Enviar',
    'auth.loading': 'Cargando...',
    'auth.error': 'Error',
    'auth.success': 'Éxito',
    // Dashboard
    'dashboard.title': 'Panel de Control',
    'dashboard.welcome': 'Bienvenido de vuelta',
    'dashboard.mainBalance': 'Saldo de Billetera Principal',
    'dashboard.investmentBalance': 'Saldo de Billetera de Inversión',
    'dashboard.totalInvested': 'Total Invertido',
    'dashboard.expectedProfit': 'Ganancia Esperada',
    'dashboard.availableToWithdraw': 'Disponible para Retiro',
    'dashboard.transferFunds': 'Transferir Fondos',
    'dashboard.from': 'De',
    'dashboard.to': 'Para',
    'dashboard.amount': 'Cantidad',
    'dashboard.submit': 'Enviar Transferencia',
    // Deposit
    'deposit.title': 'Depositar Fondos',
    'deposit.subtitle': 'Financia tu cuenta para comenzar a invertir',
    'deposit.bitcoinAddress': 'Dirección de Depósito de Bitcoin',
    'deposit.bitcoinAddressDesc': 'Envía Bitcoin a esta dirección',
    'deposit.address': 'Dirección de Bitcoin',
    'deposit.submitProof': 'Enviar Comprobante de Depósito',
    'deposit.submitProofDesc': 'Carga el comprobante de pago después de la transferencia',
    'deposit.amountLabel': 'Cantidad (USD)',
    'deposit.proof': 'Comprobante de Pago (Captura de Pantalla/Recibo)',
    'deposit.submit': 'Enviar Solicitud de Depósito',
    'deposit.submitting': 'Enviando...',
    'deposit.requestSubmitted': 'Solicitud de Depósito Enviada',
    'deposit.requestPending': 'Tu depósito está pendiente de aprobación del administrador.',
    // Withdraw
    'withdraw.title': 'Retirar Fondos',
    'withdraw.subtitle': 'Solicita un retiro de tu cuenta',
    'withdraw.noBalance': 'Sin saldo disponible',
    'withdraw.addAccount': 'Agregar Cuenta de Retiro',
    'withdraw.selectAccount': 'Seleccionar Cuenta de Retiro',
    'withdraw.amount': 'Cantidad de Retiro',
    'withdraw.min': 'Mínimo',
    'withdraw.availableBalance': 'Saldo Disponible',
    'withdraw.submit': 'Solicitar Retiro',
    'withdraw.withdrawalRequested': 'Retiro Solicitado',
    'withdraw.withdrawalPending': 'Tu retiro está pendiente de aprobación del administrador.',
    // Investments
    'investments.title': 'Mis Inversiones',
    'investments.subtitle': 'Rastrear y administrar tus inversiones',
    'investments.amountInvested': 'Cantidad Invertida',
    'investments.expectedProfit': 'Ganancia Esperada',
    'investments.maturityDate': 'Fecha de Vencimiento',
    'investments.status': 'Estado',
    'investments.active': 'Activo',
    'investments.completed': 'Completado',
    'investments.claimProfits': 'Reclamar Ganancias',
    'investments.timeRemaining': 'Tiempo Restante',
    'investments.completed.message': '¡Tu inversión ha madurado! Reclama tus ganancias ahora haciendo clic en el botón de abajo.',
    'investments.noInvestments': 'Sin inversiones activas. ¡Comienza a invertir hoy!',
    // Plans
    'plans.title': 'Planes de Inversión',
    'plans.subtitle': 'Elige un plan de inversión que se adapte a tus objetivos',
    'plans.minimumInvestment': 'Inversión Mínima',
    'plans.expectedReturn': 'Rendimiento Esperado',
    'plans.duration': 'Duración',
    'plans.invest': 'Invertir Ahora',
    'plans.kyc.required': 'Se requiere verificación KYC antes de crear inversiones.',
    'plans.balance.insufficient': 'Saldo insuficiente. Tienes',
    'plans.balance.available': 'disponible',
    'plans.investmentStarted': 'Inversión Iniciada',
    'plans.investmentCreated': 'Tu inversión ha sido creada exitosamente.',
    // KYC
    'kyc.title': 'Conozca a su Cliente (KYC)',
    'kyc.subtitle': 'Completa tu verificación KYC para desbloquear todas las funciones',
    'kyc.status': 'Estado de KYC',
    'kyc.approved': 'Aprobado',
    'kyc.pending': 'Pendiente',
    'kyc.rejected': 'Rechazado',
    'kyc.rejected.reason': 'Motivo del Rechazo',
    'kyc.personalInfo': 'Información Personal',
    'kyc.documentVerification': 'Verificación de Documento',
    'kyc.addressVerification': 'Verificación de Dirección',
    'kyc.uploadDocument': 'Cargar Documento',
    'kyc.selectDocumentType': 'Seleccionar Tipo de Documento',
    'kyc.frontSide': 'Lado Frontal',
    'kyc.backSide': 'Lado Posterior',
    'kyc.submit': 'Enviar Solicitud KYC',
    'kyc.submitted': 'KYC Enviado',
    'kyc.submittedMessage': 'Tu solicitud KYC ha sido enviada. La revisaremos en breve.',
    'kyc.awaitingApproval': 'Esperando Aprobación',
    'kyc.approved.bonus': '¡Tu KYC ha sido aprobado! Se ha acreditado un bono en tu cuenta.',
    // Transactions
    'transactions.title': 'Historial de Transacciones',
    'transactions.subtitle': 'Ver todas tus transacciones de cuenta',
    'transactions.date': 'Fecha',
    'transactions.type': 'Tipo',
    'transactions.amount': 'Cantidad',
    'transactions.status': 'Estado',
    'transactions.pending': 'Pendiente',
    'transactions.completed': 'Completado',
    'transactions.failed': 'Fallido',
    'transactions.notFound': 'No se encontraron transacciones',
    // Profile
    'profile.title': 'Mi Perfil',
    'profile.subtitle': 'Administra tu información personal',
    'profile.personalDetails': 'Detalles Personales',
    'profile.updateProfile': 'Actualizar Perfil',
    'profile.changePassword': 'Cambiar Contraseña',
    'profile.currentPassword': 'Contraseña Actual',
    'profile.newPassword': 'Nueva Contraseña',
    'profile.confirmNewPassword': 'Confirmar Nueva Contraseña',
    'profile.updatePassword': 'Actualizar Contraseña',
    // Admin Dashboard
    'admin.dashboard': 'Panel de Control de Administrador',
    'admin.totalUsers': 'Usuarios Totales',
    'admin.pendingKYC': 'KYC Pendiente',
    'admin.verifiedUsers': 'Usuarios Verificados',
    'admin.totalDeposits': 'Depósitos Totales',
    'admin.totalWithdrawals': 'Retiros Totales',
    'admin.activeInvestments': 'Inversiones Activas',
    'admin.pendingDeposits': 'Depósitos Pendientes',
    'admin.pendingWithdrawals': 'Retiros Pendientes',
    'admin.viewDetails': 'Ver Detalles',
    'admin.settings': 'Configuración',
    'admin.settingsTitle': 'Configuración del Sitio Web',
    'admin.settingsSubtitle': 'Administra la configuración del sitio web',
    'admin.depositInfo': 'Información de Depósito',
    'admin.bitcoinAddress': 'Dirección de Depósito de Bitcoin',
    'admin.bitcoinQRCode': 'Código QR de Bitcoin',
    'admin.uploadQRCode': 'Cargar Imagen de Código QR',
    'admin.companyInfo': 'Información de la Empresa',
    'admin.companyAddress': 'Dirección de la Empresa',
    'admin.companyPhone': 'Teléfono de la Empresa',
    'admin.companyEmail': 'Correo Electrónico de la Empresa',
    'admin.save': 'Guardar Configuración',
    'admin.saved': 'Configuración guardada exitosamente',
    'admin.users': 'Usuarios',
    'admin.deposits': 'Depósitos',
    'admin.withdrawals': 'Retiros',
    'admin.kyc': 'Administración de KYC',
    'admin.approveKYC': 'Aprobar KYC',
    'admin.rejectKYC': 'Rechazar KYC',
    'admin.approveDeposit': 'Aprobar Depósito',
    'admin.rejectDeposit': 'Rechazar Depósito',
    'admin.approveWithdrawal': 'Aprobar Retiro',
    'admin.rejectWithdrawal': 'Rechazar Retiro',
    // Pages
    'page.termsTitle': 'Términos y Condiciones',
    'page.privacyTitle': 'Política de Privacidad',
    'page.aboutUs': 'Acerca de Nosotros',
    'page.contactUs': 'Contáctenos',
    'page.howToJoin': 'Cómo Unirse',
    // Footer
    'footer.tagline': 'Su socio de confianza en la construcción de riqueza a través de inversiones inteligentes',
    'footer.contact': 'Contacto',
    'footer.quickLinks': 'Enlaces Rápidos',
    'footer.about': 'Acerca de Nosotros',
    'footer.investmentOptions': 'Opciones de Inversión',
    'footer.openAccount': 'Abrir Cuenta',
    'footer.login': 'Iniciar Sesión',
    'footer.legal': 'Legal',
    'footer.privacyPolicy': 'Política de Privacidad',
    'footer.termsConditions': 'Términos y Condiciones',
    'footer.riskDisclosure': 'Divulgación de Riesgos',
    'footer.compliance': 'Cumplimiento',
    'footer.allRights': 'Todos los derechos reservados.',
    // Common
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.confirm': 'Confirmar',
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.back': 'Atrás',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.export': 'Exportar',
    'common.download': 'Descargar',
    'common.upload': 'Cargar',
    'common.language': 'Idioma',
    'common.theme': 'Tema',
    'common.currency': 'Moneda',
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.investments': 'Investissements',
    'nav.crypto': 'Cryptomonnaies',
    'nav.realestate': 'Immobilier',
    'nav.oilgas': 'Pétrole et Gaz',
    'nav.nft': 'NFT',
    'nav.retirement': 'Retraite',
    'nav.loan': 'Prêt',
    'nav.company': 'Entreprise',
    'nav.dashboard': 'Tableau de Bord',
    'nav.deposit': 'Dépôt',
    'nav.withdraw': 'Retrait',
    'nav.investments.menu': 'Investissements',
    'nav.plans': 'Plans d\'Investissement',
    'nav.transactions': 'Transactions',
    'nav.kyc': 'KYC',
    'nav.profile': 'Profil',
    'nav.settings': 'Paramètres',
    'nav.logout': 'Déconnexion',
    // Hero Section
    'hero.badge': 'Approuvé par plus de 50 000 investisseurs dans le monde',
    'hero.title.part1': 'Les investisseurs plus intelligents sont ici.',
    'hero.title.part2': 'Vous devriez être ici aussi.',
    'hero.subtitle': 'Nos professionnels et nos outils de pointe sont unis pour faire une chose: faire de vous un investisseur plus intelligent et plus rentable.',
    'hero.btn.openAccount': 'Ouvrir un Compte Gratuit',
    'hero.btn.login': 'Se Connecter à Votre Compte',
    'hero.stats.aum': 'Actifs Sous Gestion',
    'hero.stats.investors': 'Investisseurs Actifs',
    'hero.stats.experience': 'Années d\'Expérience',
    // About Section
    'about.title': 'À Propos de',
    'about.titleHighlight': 'Whitestones Markets',
    'about.description': 'Whitestones Markets est une plateforme d\'investissement mondiale de premier plan qui combine une technologie de pointe avec des conseils financiers d\'experts. Nous permettons aux investisseurs du monde entier de prendre des décisions plus intelligentes et d\'atteindre leurs objectifs financiers grâce à des opportunités d\'investissement diversifiées.',
    'about.secure.title': 'Plateforme Sécurisée',
    'about.secure.desc': 'Sécurité de niveau bancaire avec cryptage avancé protégeant vos investissements 24h/24 et 7j/7',
    'about.award.title': 'Primé',
    'about.award.desc': 'Reconnu mondialement pour l\'excellence en services financiers et innovation',
    'about.expert.title': 'Équipe d\'Experts',
    'about.expert.desc': 'Conseillers professionnels avec des décennies d\'expérience combinée sur les marchés mondiaux',
    'about.results.title': 'Résultats Prouvés',
    'about.results.desc': 'Rendements cohérents et investisseurs satisfaits dans plusieurs classes d\'actifs',
    // Investment Plans Section
    'investmentPlans.title': 'Choisissez Votre',
    'investmentPlans.titleHighlight': 'Plan d\'Investissement',
    'investmentPlans.subtitle': 'Sélectionnez le plan qui correspond le mieux à vos objectifs d\'investissement et commencez à gagner aujourd\'hui',
    'investmentPlans.totalROI': 'ROI Total',
    'investmentPlans.unlimited': 'Illimité',
    'investmentPlans.duration': 'Durée',
    'investmentPlans.getStarted': 'Commencer',
    'investmentPlans.loading': 'Chargement des plans...',
    // CTA
    'cta.openAccount': 'Ouvrir un Compte Gratuit',
    'cta.login': 'Se Connecter',
    'auth.signup': 'Créer un Compte',
    'auth.login': 'Se Connecter au Compte',
    'auth.fullName': 'Nom Complet',
    'auth.email': 'Adresse E-mail',
    'auth.password': 'Mot de Passe',
    'auth.confirmPassword': 'Confirmer le Mot de Passe',
    'auth.phone': 'Numéro de Téléphone',
    'auth.dob': 'Date de Naissance',
    'auth.country': 'Pays',
    'auth.terms': "J'accepte les Termes et Conditions",
    'auth.haveAccount': 'Vous avez déjà un compte?',
    'auth.noAccount': 'Nouveau sur notre plateforme?',
    'auth.signInInstead': 'Se connecter à la place',
    'auth.createAccount': 'Créer un compte',
    'auth.rememberMe': 'Se souvenir de moi',
    'auth.forgotCode': 'Code oublié?',
    'auth.submit': 'Soumettre',
    'auth.loading': 'Chargement...',
    'auth.error': 'Erreur',
    'auth.success': 'Succès',
    'dashboard.title': 'Tableau de Bord',
    'dashboard.welcome': 'Bienvenue',
    'dashboard.mainBalance': 'Solde du Portefeuille Principal',
    'dashboard.investmentBalance': 'Solde du Portefeuille d\'Investissement',
    'dashboard.totalInvested': 'Total Investi',
    'dashboard.expectedProfit': 'Bénéfice Attendu',
    'dashboard.availableToWithdraw': 'Disponible pour le Retrait',
    'dashboard.transferFunds': 'Transférer des Fonds',
    'dashboard.from': 'De',
    'dashboard.to': 'À',
    'dashboard.amount': 'Montant',
    'dashboard.submit': 'Soumettre le Transfert',
    'deposit.title': 'Déposer des Fonds',
    'deposit.subtitle': 'Financez votre compte pour commencer à investir',
    'deposit.bitcoinAddress': 'Adresse de Dépôt Bitcoin',
    'deposit.bitcoinAddressDesc': 'Envoyer Bitcoin à cette adresse',
    'deposit.address': 'Adresse Bitcoin',
    'deposit.submitProof': 'Soumettre la Preuve de Dépôt',
    'deposit.submitProofDesc': 'Télécharger la preuve de paiement après le transfert',
    'deposit.amountLabel': 'Montant (USD)',
    'deposit.proof': 'Preuve de Paiement (Capture d\'écran/Reçu)',
    'deposit.submit': 'Soumettre la Demande de Dépôt',
    'deposit.submitting': 'Soumission en cours...',
    'deposit.requestSubmitted': 'Demande de Dépôt Soumise',
    'deposit.requestPending': 'Votre dépôt est en attente d\'approbation de l\'administrateur.',
    'withdraw.title': 'Retirer des Fonds',
    'withdraw.subtitle': 'Demander un retrait de votre compte',
    'withdraw.noBalance': 'Aucun solde disponible',
    'withdraw.addAccount': 'Ajouter un Compte de Retrait',
    'withdraw.selectAccount': 'Sélectionner Compte de Retrait',
    'withdraw.amount': 'Montant du Retrait',
    'withdraw.min': 'Minimum',
    'withdraw.availableBalance': 'Solde Disponible',
    'withdraw.submit': 'Demander le Retrait',
    'withdraw.withdrawalRequested': 'Retrait Demandé',
    'withdraw.withdrawalPending': 'Votre retrait est en attente d\'approbation de l\'administrateur.',
    'investments.title': 'Mes Investissements',
    'investments.subtitle': 'Suivre et gérer vos investissements',
    'investments.amountInvested': 'Montant Investi',
    'investments.expectedProfit': 'Bénéfice Attendu',
    'investments.maturityDate': 'Date d\'Échéance',
    'investments.status': 'Statut',
    'investments.active': 'Actif',
    'investments.completed': 'Complété',
    'investments.claimProfits': 'Réclamer les Bénéfices',
    'investments.timeRemaining': 'Temps Restant',
    'investments.completed.message': 'Votre investissement a mûr! Réclamez vos bénéfices maintenant en cliquant sur le bouton ci-dessous.',
    'investments.noInvestments': 'Aucun investissement actif. Commencez à investir aujourd\'hui!',
    'plans.title': 'Plans d\'Investissement',
    'plans.subtitle': 'Choisissez un plan d\'investissement qui correspond à vos objectifs',
    'plans.minimumInvestment': 'Investissement Minimum',
    'plans.expectedReturn': 'Rendement Attendu',
    'plans.duration': 'Durée',
    'plans.invest': 'Investir Maintenant',
    'plans.kyc.required': 'La vérification KYC est requise avant de créer des investissements.',
    'plans.balance.insufficient': 'Solde insuffisant. Vous avez',
    'plans.balance.available': 'disponible',
    'plans.investmentStarted': 'Investissement Commencé',
    'plans.investmentCreated': 'Votre investissement a été créé avec succès.',
    'kyc.title': 'Connaître votre Client (KYC)',
    'kyc.subtitle': 'Complétez votre vérification KYC pour déverrouiller toutes les fonctionnalités',
    'kyc.status': 'Statut KYC',
    'kyc.approved': 'Approuvé',
    'kyc.pending': 'En Attente',
    'kyc.rejected': 'Rejeté',
    'kyc.rejected.reason': 'Motif du Rejet',
    'kyc.personalInfo': 'Informations Personnelles',
    'kyc.documentVerification': 'Vérification du Document',
    'kyc.addressVerification': 'Vérification d\'Adresse',
    'kyc.uploadDocument': 'Télécharger le Document',
    'kyc.selectDocumentType': 'Sélectionner Type de Document',
    'kyc.frontSide': 'Face Avant',
    'kyc.backSide': 'Face Arrière',
    'kyc.submit': 'Soumettre la Demande KYC',
    'kyc.submitted': 'KYC Soumis',
    'kyc.submittedMessage': 'Votre demande KYC a été soumise. Nous l\'examinerons bientôt.',
    'kyc.awaitingApproval': 'En Attente d\'Approbation',
    'kyc.approved.bonus': 'Votre KYC a été approuvé! Un bonus a été crédité sur votre compte.',
    'transactions.title': 'Historique des Transactions',
    'transactions.subtitle': 'Voir tous vos transactions de compte',
    'transactions.date': 'Date',
    'transactions.type': 'Type',
    'transactions.amount': 'Montant',
    'transactions.status': 'Statut',
    'transactions.pending': 'En Attente',
    'transactions.completed': 'Complété',
    'transactions.failed': 'Échoué',
    'transactions.notFound': 'Aucune transaction trouvée',
    'profile.title': 'Mon Profil',
    'profile.subtitle': 'Gérez vos informations personnelles',
    'profile.personalDetails': 'Détails Personnels',
    'profile.updateProfile': 'Mettre à Jour le Profil',
    'profile.changePassword': 'Changer le Mot de Passe',
    'profile.currentPassword': 'Mot de Passe Actuel',
    'profile.newPassword': 'Nouveau Mot de Passe',
    'profile.confirmNewPassword': 'Confirmer le Nouveau Mot de Passe',
    'profile.updatePassword': 'Mettre à Jour le Mot de Passe',
    'admin.dashboard': 'Tableau de Bord Admin',
    'admin.totalUsers': 'Utilisateurs Totaux',
    'admin.pendingKYC': 'KYC En Attente',
    'admin.verifiedUsers': 'Utilisateurs Vérifiés',
    'admin.totalDeposits': 'Dépôts Totaux',
    'admin.totalWithdrawals': 'Retraits Totaux',
    'admin.activeInvestments': 'Investissements Actifs',
    'admin.pendingDeposits': 'Dépôts En Attente',
    'admin.pendingWithdrawals': 'Retraits En Attente',
    'admin.viewDetails': 'Voir les Détails',
    'admin.settings': 'Paramètres',
    'admin.settingsTitle': 'Paramètres du Site Web',
    'admin.settingsSubtitle': 'Gérer la configuration du site web',
    'admin.depositInfo': 'Informations de Dépôt',
    'admin.bitcoinAddress': 'Adresse de Dépôt Bitcoin',
    'admin.bitcoinQRCode': 'Code QR Bitcoin',
    'admin.uploadQRCode': 'Télécharger l\'Image du Code QR',
    'admin.companyInfo': 'Informations de l\'Entreprise',
    'admin.companyAddress': 'Adresse de l\'Entreprise',
    'admin.companyPhone': 'Téléphone de l\'Entreprise',
    'admin.companyEmail': 'E-mail de l\'Entreprise',
    'admin.save': 'Enregistrer les Paramètres',
    'admin.saved': 'Paramètres enregistrés avec succès',
    'admin.users': 'Utilisateurs',
    'admin.deposits': 'Dépôts',
    'admin.withdrawals': 'Retraits',
    'admin.kyc': 'Gestion KYC',
    'admin.approveKYC': 'Approuver KYC',
    'admin.rejectKYC': 'Rejeter KYC',
    'admin.approveDeposit': 'Approuver le Dépôt',
    'admin.rejectDeposit': 'Rejeter le Dépôt',
    'admin.approveWithdrawal': 'Approuver le Retrait',
    'admin.rejectWithdrawal': 'Rejeter le Retrait',
    'page.termsTitle': 'Termes et Conditions',
    'page.privacyTitle': 'Politique de Confidentialité',
    'page.aboutUs': 'À Propos de Nous',
    'page.contactUs': 'Nous Contacter',
    'page.howToJoin': 'Comment Rejoindre',
    // Footer
    'footer.tagline': 'Votre partenaire de confiance pour construire votre patrimoine grâce à des investissements intelligents',
    'footer.contact': 'Contact',
    'footer.quickLinks': 'Liens Rapides',
    'footer.about': 'À Propos de Nous',
    'footer.investmentOptions': 'Options d\'Investissement',
    'footer.openAccount': 'Ouvrir un Compte',
    'footer.login': 'Se Connecter',
    'footer.legal': 'Mentions Légales',
    'footer.privacyPolicy': 'Politique de Confidentialité',
    'footer.termsConditions': 'Termes et Conditions',
    'footer.riskDisclosure': 'Divulgation des Risques',
    'footer.compliance': 'Conformité',
    'footer.allRights': 'Tous droits réservés.',
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.confirm': 'Confirmer',
    'common.cancel': 'Annuler',
    'common.save': 'Enregistrer',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.back': 'Retour',
    'common.next': 'Suivant',
    'common.previous': 'Précédent',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.export': 'Exporter',
    'common.download': 'Télécharger',
    'common.upload': 'Télécharger',
    'common.language': 'Langue',
    'common.theme': 'Thème',
    'common.currency': 'Devise',
  },
  it: {
    'nav.home': 'Home',
    'nav.investments': 'Investimenti',
    'nav.crypto': 'Criptovalute',
    'nav.realestate': 'Immobiliare',
    'nav.oilgas': 'Petrolio e Gas',
    'nav.nft': 'NFT',
    'nav.retirement': 'Pensione',
    'nav.loan': 'Prestito',
    'nav.company': 'Azienda',
    'nav.dashboard': 'Pannello',
    'nav.deposit': 'Deposito',
    'nav.withdraw': 'Prelievo',
    'nav.investments.menu': 'Investimenti',
    'nav.plans': 'Piani di Investimento',
    'nav.transactions': 'Transazioni',
    'nav.kyc': 'KYC',
    'nav.profile': 'Profilo',
    'nav.settings': 'Impostazioni',
    'nav.logout': 'Esci',
    // Hero Section
    'hero.badge': 'Di fiducia da oltre 50.000 investitori in tutto il mondo',
    'hero.title.part1': 'Gli investitori più intelligenti sono qui.',
    'hero.title.part2': 'Dovresti essere qui anche tu.',
    'hero.subtitle': 'I nostri professionisti e gli strumenti leader del settore sono uniti per fare una cosa: renderti un investitore più intelligente e redditizio.',
    'hero.btn.openAccount': 'Apri un Conto Gratuito',
    'hero.btn.login': 'Accedi al Tuo Account',
    'hero.stats.aum': 'Patrimonio in Gestione',
    'hero.stats.investors': 'Investitori Attivi',
    'hero.stats.experience': 'Anni di Esperienza',
    // About Section
    'about.title': 'Chi È',
    'about.titleHighlight': 'Whitestones Markets',
    'about.description': 'Whitestones Markets è una piattaforma di investimento globale leader che combina tecnologia all\'avanguardia con consulenza finanziaria esperta. Diamo potere agli investitori di tutto il mondo per prendere decisioni più intelligenti e raggiungere i loro obiettivi finanziari attraverso opportunità di investimento diversificate.',
    'about.secure.title': 'Piattaforma Sicura',
    'about.secure.desc': 'Sicurezza di livello bancario con crittografia avanzata che protegge i tuoi investimenti 24/7',
    'about.award.title': 'Premiato',
    'about.award.desc': 'Riconosciuto a livello mondiale per l\'eccellenza nei servizi finanziari e nell\'innovazione',
    'about.expert.title': 'Team di Esperti',
    'about.expert.desc': 'Consulenti professionali con decenni di esperienza combinata nei mercati globali',
    'about.results.title': 'Risultati Comprovati',
    'about.results.desc': 'Rendimenti costanti e investitori soddisfatti in molteplici classi di attività',
    // Investment Plans Section
    'investmentPlans.title': 'Scegli il Tuo',
    'investmentPlans.titleHighlight': 'Piano di Investimento',
    'investmentPlans.subtitle': 'Seleziona il piano che meglio si adatta ai tuoi obiettivi di investimento e inizia a guadagnare oggi',
    'investmentPlans.totalROI': 'ROI Totale',
    'investmentPlans.unlimited': 'Illimitato',
    'investmentPlans.duration': 'Durata',
    'investmentPlans.getStarted': 'Inizia',
    'investmentPlans.loading': 'Caricamento piani...',
    // CTA
    'cta.openAccount': 'Apri un Conto Gratuito',
    'cta.login': 'Accedi',
    'auth.signup': 'Crea un Account',
    'auth.login': 'Accedi all\'Account',
    'auth.fullName': 'Nome Completo',
    'auth.email': 'Indirizzo Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Conferma Password',
    'auth.phone': 'Numero di Telefono',
    'auth.dob': 'Data di Nascita',
    'auth.country': 'Paese',
    'auth.terms': 'Accetto i Termini e le Condizioni',
    'auth.haveAccount': 'Hai già un account?',
    'auth.noAccount': 'Nuovo sulla nostra piattaforma?',
    'auth.signInInstead': 'Accedi invece',
    'auth.createAccount': 'Crea un account',
    'auth.rememberMe': 'Ricordami',
    'auth.forgotCode': 'Codice dimenticato?',
    'auth.submit': 'Invia',
    'auth.loading': 'Caricamento...',
    'auth.error': 'Errore',
    'auth.success': 'Successo',
    'dashboard.title': 'Pannello',
    'dashboard.welcome': 'Bentornato',
    'dashboard.mainBalance': 'Saldo Portafoglio Principale',
    'dashboard.investmentBalance': 'Saldo Portafoglio Investimento',
    'dashboard.totalInvested': 'Totale Investito',
    'dashboard.expectedProfit': 'Profitto Atteso',
    'dashboard.availableToWithdraw': 'Disponibile per il Prelievo',
    'dashboard.transferFunds': 'Trasferisci Fondi',
    'dashboard.from': 'Da',
    'dashboard.to': 'A',
    'dashboard.amount': 'Importo',
    'dashboard.submit': 'Invia Trasferimento',
    'deposit.title': 'Deposita Fondi',
    'deposit.subtitle': 'Finanzia il tuo account per iniziare a investire',
    'deposit.bitcoinAddress': 'Indirizzo di Deposito Bitcoin',
    'deposit.bitcoinAddressDesc': 'Invia Bitcoin a questo indirizzo',
    'deposit.address': 'Indirizzo Bitcoin',
    'deposit.submitProof': 'Invia Prova di Deposito',
    'deposit.submitProofDesc': 'Carica la prova di pagamento dopo il trasferimento',
    'deposit.amountLabel': 'Importo (USD)',
    'deposit.proof': 'Prova di Pagamento (Schermata/Ricevuta)',
    'deposit.submit': 'Invia Richiesta di Deposito',
    'deposit.submitting': 'Invio in corso...',
    'deposit.requestSubmitted': 'Richiesta di Deposito Inviata',
    'deposit.requestPending': 'Il tuo deposito è in attesa di approvazione da parte dell\'amministratore.',
    'withdraw.title': 'Preleva Fondi',
    'withdraw.subtitle': 'Richiedi un prelievo dal tuo account',
    'withdraw.noBalance': 'Nessun saldo disponibile',
    'withdraw.addAccount': 'Aggiungi Account di Prelievo',
    'withdraw.selectAccount': 'Seleziona Account di Prelievo',
    'withdraw.amount': 'Importo del Prelievo',
    'withdraw.min': 'Minimo',
    'withdraw.availableBalance': 'Saldo Disponibile',
    'withdraw.submit': 'Richiedi Prelievo',
    'withdraw.withdrawalRequested': 'Prelievo Richiesto',
    'withdraw.withdrawalPending': 'Il tuo prelievo è in attesa di approvazione da parte dell\'amministratore.',
    'investments.title': 'I Miei Investimenti',
    'investments.subtitle': 'Traccia e gestisci i tuoi investimenti',
    'investments.amountInvested': 'Importo Investito',
    'investments.expectedProfit': 'Profitto Atteso',
    'investments.maturityDate': 'Data di Scadenza',
    'investments.status': 'Stato',
    'investments.active': 'Attivo',
    'investments.completed': 'Completato',
    'investments.claimProfits': 'Reclama Profitti',
    'investments.timeRemaining': 'Tempo Rimanente',
    'investments.completed.message': 'Il tuo investimento è scaduto! Reclama i tuoi profitti ora facendo clic sul pulsante sottostante.',
    'investments.noInvestments': 'Nessun investimento attivo. Inizia a investire oggi!',
    'plans.title': 'Piani di Investimento',
    'plans.subtitle': 'Scegli un piano di investimento che si adatta ai tuoi obiettivi',
    'plans.minimumInvestment': 'Investimento Minimo',
    'plans.expectedReturn': 'Rendimento Atteso',
    'plans.duration': 'Durata',
    'plans.invest': 'Investi Ora',
    'plans.kyc.required': 'La verifica KYC è necessaria prima di creare investimenti.',
    'plans.balance.insufficient': 'Saldo insufficiente. Hai',
    'plans.balance.available': 'disponibile',
    'plans.investmentStarted': 'Investimento Avviato',
    'plans.investmentCreated': 'Il tuo investimento è stato creato con successo.',
    'kyc.title': 'Conosci il tuo Cliente (KYC)',
    'kyc.subtitle': 'Completa la tua verifica KYC per sbloccare tutte le funzionalità',
    'kyc.status': 'Stato KYC',
    'kyc.approved': 'Approvato',
    'kyc.pending': 'In Sospeso',
    'kyc.rejected': 'Rifiutato',
    'kyc.rejected.reason': 'Motivo del Rifiuto',
    'kyc.personalInfo': 'Informazioni Personali',
    'kyc.documentVerification': 'Verifica Documento',
    'kyc.addressVerification': 'Verifica Indirizzo',
    'kyc.uploadDocument': 'Carica Documento',
    'kyc.selectDocumentType': 'Seleziona Tipo di Documento',
    'kyc.frontSide': 'Lato Anteriore',
    'kyc.backSide': 'Lato Posteriore',
    'kyc.submit': 'Invia Richiesta KYC',
    'kyc.submitted': 'KYC Inviato',
    'kyc.submittedMessage': 'La tua richiesta KYC è stata inviata. La esamineremo presto.',
    'kyc.awaitingApproval': 'In Attesa di Approvazione',
    'kyc.approved.bonus': 'Il tuo KYC è stato approvato! Un bonus è stato accreditato sul tuo account.',
    'transactions.title': 'Cronologia Transazioni',
    'transactions.subtitle': 'Visualizza tutte le transazioni del tuo account',
    'transactions.date': 'Data',
    'transactions.type': 'Tipo',
    'transactions.amount': 'Importo',
    'transactions.status': 'Stato',
    'transactions.pending': 'In Sospeso',
    'transactions.completed': 'Completato',
    'transactions.failed': 'Fallito',
    'transactions.notFound': 'Nessuna transazione trovata',
    'profile.title': 'Il Mio Profilo',
    'profile.subtitle': 'Gestisci le tue informazioni personali',
    'profile.personalDetails': 'Dettagli Personali',
    'profile.updateProfile': 'Aggiorna Profilo',
    'profile.changePassword': 'Cambio Password',
    'profile.currentPassword': 'Password Attuale',
    'profile.newPassword': 'Nuova Password',
    'profile.confirmNewPassword': 'Conferma Nuova Password',
    'profile.updatePassword': 'Aggiorna Password',
    'admin.dashboard': 'Pannello Admin',
    'admin.totalUsers': 'Utenti Totali',
    'admin.pendingKYC': 'KYC in Sospeso',
    'admin.verifiedUsers': 'Utenti Verificati',
    'admin.totalDeposits': 'Depositi Totali',
    'admin.totalWithdrawals': 'Prelievi Totali',
    'admin.activeInvestments': 'Investimenti Attivi',
    'admin.pendingDeposits': 'Depositi in Sospeso',
    'admin.pendingWithdrawals': 'Prelievi in Sospeso',
    'admin.viewDetails': 'Visualizza Dettagli',
    'admin.settings': 'Impostazioni',
    'admin.settingsTitle': 'Impostazioni Sito Web',
    'admin.settingsSubtitle': 'Gestisci la configurazione del sito web',
    'admin.depositInfo': 'Informazioni Deposito',
    'admin.bitcoinAddress': 'Indirizzo di Deposito Bitcoin',
    'admin.bitcoinQRCode': 'Codice QR Bitcoin',
    'admin.uploadQRCode': 'Carica Immagine Codice QR',
    'admin.companyInfo': 'Informazioni Azienda',
    'admin.companyAddress': 'Indirizzo Azienda',
    'admin.companyPhone': 'Telefono Azienda',
    'admin.companyEmail': 'Email Azienda',
    'admin.save': 'Salva Impostazioni',
    'admin.saved': 'Impostazioni salvate con successo',
    'admin.users': 'Utenti',
    'admin.deposits': 'Depositi',
    'admin.withdrawals': 'Prelievi',
    'admin.kyc': 'Gestione KYC',
    'admin.approveKYC': 'Approva KYC',
    'admin.rejectKYC': 'Rifiuta KYC',
    'admin.approveDeposit': 'Approva Deposito',
    'admin.rejectDeposit': 'Rifiuta Deposito',
    'admin.approveWithdrawal': 'Approva Prelievo',
    'admin.rejectWithdrawal': 'Rifiuta Prelievo',
    'page.termsTitle': 'Termini e Condizioni',
    'page.privacyTitle': 'Politica sulla Privacy',
    'page.aboutUs': 'Chi Siamo',
    'page.contactUs': 'Contattaci',
    'page.howToJoin': 'Come Aderire',
    // Footer
    'footer.tagline': 'Il tuo partner di fiducia nella costruzione della ricchezza attraverso investimenti intelligenti',
    'footer.contact': 'Contatto',
    'footer.quickLinks': 'Link Veloci',
    'footer.about': 'Chi Siamo',
    'footer.investmentOptions': 'Opzioni di Investimento',
    'footer.openAccount': 'Apri Account',
    'footer.login': 'Accedi',
    'footer.legal': 'Legale',
    'footer.privacyPolicy': 'Politica sulla Privacy',
    'footer.termsConditions': 'Termini e Condizioni',
    'footer.riskDisclosure': 'Informativa sui Rischi',
    'footer.compliance': 'Conformità',
    'footer.allRights': 'Tutti i diritti riservati.',
    'common.loading': 'Caricamento...',
    'common.error': 'Errore',
    'common.success': 'Successo',
    'common.confirm': 'Conferma',
    'common.cancel': 'Annulla',
    'common.save': 'Salva',
    'common.delete': 'Elimina',
    'common.edit': 'Modifica',
    'common.back': 'Indietro',
    'common.next': 'Successivo',
    'common.previous': 'Precedente',
    'common.search': 'Cerca',
    'common.filter': 'Filtra',
    'common.export': 'Esporta',
    'common.download': 'Scarica',
    'common.upload': 'Carica',
    'common.language': 'Lingua',
    'common.theme': 'Tema',
    'common.currency': 'Valuta',
  },
  pt: {
    'nav.home': 'Início',
    'nav.investments': 'Investimentos',
    'nav.crypto': 'Criptomoedas',
    'nav.realestate': 'Imóveis',
    'nav.oilgas': 'Petróleo e Gás',
    'nav.nft': 'NFT',
    'nav.retirement': 'Aposentadoria',
    'nav.loan': 'Empréstimo',
    'nav.company': 'Empresa',
    'nav.dashboard': 'Painel',
    'nav.deposit': 'Depositar',
    'nav.withdraw': 'Sacar',
    'nav.investments.menu': 'Investimentos',
    'nav.plans': 'Planos de Investimento',
    'nav.transactions': 'Transações',
    'nav.kyc': 'KYC',
    'nav.profile': 'Perfil',
    'nav.settings': 'Configurações',
    'nav.logout': 'Sair',
    // Hero Section
    'hero.badge': 'Confiado por mais de 50.000 investidores em todo o mundo',
    'hero.title.part1': 'Investidores mais inteligentes estão aqui.',
    'hero.title.part2': 'Você também deveria estar aqui.',
    'hero.subtitle': 'Nossos profissionais e ferramentas líderes do setor estão unidos para fazer uma coisa: torná-lo um investidor mais inteligente e lucrativo.',
    'hero.btn.openAccount': 'Abrir uma Conta Gratuita',
    'hero.btn.login': 'Entrar na Sua Conta',
    'hero.stats.aum': 'Ativos Sob Gestão',
    'hero.stats.investors': 'Investidores Ativos',
    'hero.stats.experience': 'Anos de Experiência',
    // About Section
    'about.title': 'Sobre',
    'about.titleHighlight': 'Whitestones Markets',
    'about.description': 'Whitestones Markets é uma plataforma de investimento global líder que combina tecnologia de ponta com orientação financeira especializada. Capacitamos investidores em todo o mundo para tomar decisões mais inteligentes e alcançar seus objetivos financeiros através de oportunidades de investimento diversificadas.',
    'about.secure.title': 'Plataforma Segura',
    'about.secure.desc': 'Segurança de nível bancário com criptografia avançada protegendo seus investimentos 24/7',
    'about.award.title': 'Premiado',
    'about.award.desc': 'Reconhecido globalmente pela excelência em serviços financeiros e inovação',
    'about.expert.title': 'Equipe Especializada',
    'about.expert.desc': 'Consultores profissionais com décadas de experiência combinada em mercados globais',
    'about.results.title': 'Resultados Comprovados',
    'about.results.desc': 'Retornos consistentes e investidores satisfeitos em múltiplas classes de ativos',
    // Investment Plans Section
    'investmentPlans.title': 'Escolha Seu',
    'investmentPlans.titleHighlight': 'Plano de Investimento',
    'investmentPlans.subtitle': 'Selecione o plano que melhor se adapta aos seus objetivos de investimento e comece a ganhar hoje',
    'investmentPlans.totalROI': 'ROI Total',
    'investmentPlans.unlimited': 'Ilimitado',
    'investmentPlans.duration': 'Duração',
    'investmentPlans.getStarted': 'Começar',
    'investmentPlans.loading': 'Carregando planos...',
    // CTA
    'cta.openAccount': 'Abrir uma Conta Gratuita',
    'cta.login': 'Entrar',
    'auth.signup': 'Criar uma Conta',
    'auth.login': 'Entrar na Conta',
    'auth.fullName': 'Nome Completo',
    'auth.email': 'Endereço de E-mail',
    'auth.password': 'Senha',
    'auth.confirmPassword': 'Confirmar Senha',
    'auth.phone': 'Número de Telefone',
    'auth.dob': 'Data de Nascimento',
    'auth.country': 'País',
    'auth.terms': 'Eu concordo com os Termos e Condições',
    'auth.haveAccount': 'Já tem uma conta?',
    'auth.noAccount': 'Novo em nossa plataforma?',
    'auth.signInInstead': 'Entrar em vez disso',
    'auth.createAccount': 'Criar uma conta',
    'auth.rememberMe': 'Lembrar de mim',
    'auth.forgotCode': 'Esqueceu o código?',
    'auth.submit': 'Enviar',
    'auth.loading': 'Carregando...',
    'auth.error': 'Erro',
    'auth.success': 'Sucesso',
    'dashboard.title': 'Painel',
    'dashboard.welcome': 'Bem-vindo de volta',
    'dashboard.mainBalance': 'Saldo da Carteira Principal',
    'dashboard.investmentBalance': 'Saldo da Carteira de Investimento',
    'dashboard.totalInvested': 'Total Investido',
    'dashboard.expectedProfit': 'Lucro Esperado',
    'dashboard.availableToWithdraw': 'Disponível para Saque',
    'dashboard.transferFunds': 'Transferir Fundos',
    'dashboard.from': 'De',
    'dashboard.to': 'Para',
    'dashboard.amount': 'Quantidade',
    'dashboard.submit': 'Enviar Transferência',
    'deposit.title': 'Depositar Fundos',
    'deposit.subtitle': 'Financie sua conta para começar a investir',
    'deposit.bitcoinAddress': 'Endereço de Depósito de Bitcoin',
    'deposit.bitcoinAddressDesc': 'Envie Bitcoin para este endereço',
    'deposit.address': 'Endereço de Bitcoin',
    'deposit.submitProof': 'Enviar Comprovante de Depósito',
    'deposit.submitProofDesc': 'Carregue o comprovante de pagamento após a transferência',
    'deposit.amountLabel': 'Quantidade (USD)',
    'deposit.proof': 'Comprovante de Pagamento (Captura de tela/Recibo)',
    'deposit.submit': 'Enviar Solicitação de Depósito',
    'deposit.submitting': 'Enviando...',
    'deposit.requestSubmitted': 'Solicitação de Depósito Enviada',
    'deposit.requestPending': 'Seu depósito está aguardando aprovação do administrador.',
    'withdraw.title': 'Sacar Fundos',
    'withdraw.subtitle': 'Solicite um saque de sua conta',
    'withdraw.noBalance': 'Sem saldo disponível',
    'withdraw.addAccount': 'Adicionar Conta de Saque',
    'withdraw.selectAccount': 'Selecionar Conta de Saque',
    'withdraw.amount': 'Valor do Saque',
    'withdraw.min': 'Mínimo',
    'withdraw.availableBalance': 'Saldo Disponível',
    'withdraw.submit': 'Solicitar Saque',
    'withdraw.withdrawalRequested': 'Saque Solicitado',
    'withdraw.withdrawalPending': 'Seu saque está aguardando aprovação do administrador.',
    'investments.title': 'Meus Investimentos',
    'investments.subtitle': 'Acompanhe e gerencie seus investimentos',
    'investments.amountInvested': 'Quantidade Investida',
    'investments.expectedProfit': 'Lucro Esperado',
    'investments.maturityDate': 'Data de Vencimento',
    'investments.status': 'Status',
    'investments.active': 'Ativo',
    'investments.completed': 'Concluído',
    'investments.claimProfits': 'Reivindicar Lucros',
    'investments.timeRemaining': 'Tempo Restante',
    'investments.completed.message': 'Seu investimento venceu! Reivindique seus lucros agora clicando no botão abaixo.',
    'investments.noInvestments': 'Sem investimentos ativos. Comece a investir hoje!',
    'plans.title': 'Planos de Investimento',
    'plans.subtitle': 'Escolha um plano de investimento que se adeque aos seus objetivos',
    'plans.minimumInvestment': 'Investimento Mínimo',
    'plans.expectedReturn': 'Retorno Esperado',
    'plans.duration': 'Duração',
    'plans.invest': 'Investir Agora',
    'plans.kyc.required': 'Verificação KYC é necessária antes de criar investimentos.',
    'plans.balance.insufficient': 'Saldo insuficiente. Você tem',
    'plans.balance.available': 'disponível',
    'plans.investmentStarted': 'Investimento Iniciado',
    'plans.investmentCreated': 'Seu investimento foi criado com sucesso.',
    'kyc.title': 'Conheça seu Cliente (KYC)',
    'kyc.subtitle': 'Complete sua verificação KYC para desbloquear todos os recursos',
    'kyc.status': 'Status KYC',
    'kyc.approved': 'Aprovado',
    'kyc.pending': 'Pendente',
    'kyc.rejected': 'Rejeitado',
    'kyc.rejected.reason': 'Motivo da Rejeição',
    'kyc.personalInfo': 'Informações Pessoais',
    'kyc.documentVerification': 'Verificação de Documento',
    'kyc.addressVerification': 'Verificação de Endereço',
    'kyc.uploadDocument': 'Carregar Documento',
    'kyc.selectDocumentType': 'Selecionar Tipo de Documento',
    'kyc.frontSide': 'Frente',
    'kyc.backSide': 'Verso',
    'kyc.submit': 'Enviar Solicitação KYC',
    'kyc.submitted': 'KYC Enviado',
    'kyc.submittedMessage': 'Sua solicitação KYC foi enviada. Vamos analisá-la em breve.',
    'kyc.awaitingApproval': 'Aguardando Aprovação',
    'kyc.approved.bonus': 'Seu KYC foi aprovado! Um bônus foi creditado em sua conta.',
    'transactions.title': 'Histórico de Transações',
    'transactions.subtitle': 'Visualize todas as transações da sua conta',
    'transactions.date': 'Data',
    'transactions.type': 'Tipo',
    'transactions.amount': 'Quantidade',
    'transactions.status': 'Status',
    'transactions.pending': 'Pendente',
    'transactions.completed': 'Concluído',
    'transactions.failed': 'Falha',
    'transactions.notFound': 'Nenhuma transação encontrada',
    'profile.title': 'Meu Perfil',
    'profile.subtitle': 'Gerencie suas informações pessoais',
    'profile.personalDetails': 'Detalhes Pessoais',
    'profile.updateProfile': 'Atualizar Perfil',
    'profile.changePassword': 'Alterar Senha',
    'profile.currentPassword': 'Senha Atual',
    'profile.newPassword': 'Nova Senha',
    'profile.confirmNewPassword': 'Confirmar Nova Senha',
    'profile.updatePassword': 'Atualizar Senha',
    'admin.dashboard': 'Painel Admin',
    'admin.totalUsers': 'Total de Usuários',
    'admin.pendingKYC': 'KYC Pendente',
    'admin.verifiedUsers': 'Usuários Verificados',
    'admin.totalDeposits': 'Total de Depósitos',
    'admin.totalWithdrawals': 'Total de Saques',
    'admin.activeInvestments': 'Investimentos Ativos',
    'admin.pendingDeposits': 'Depósitos Pendentes',
    'admin.pendingWithdrawals': 'Saques Pendentes',
    'admin.viewDetails': 'Ver Detalhes',
    'admin.settings': 'Configurações',
    'admin.settingsTitle': 'Configurações do Site',
    'admin.settingsSubtitle': 'Gerencie a configuração do site',
    'admin.depositInfo': 'Informações de Depósito',
    'admin.bitcoinAddress': 'Endereço de Depósito de Bitcoin',
    'admin.bitcoinQRCode': 'Código QR de Bitcoin',
    'admin.uploadQRCode': 'Carregar Imagem de Código QR',
    'admin.companyInfo': 'Informações da Empresa',
    'admin.companyAddress': 'Endereço da Empresa',
    'admin.companyPhone': 'Telefone da Empresa',
    'admin.companyEmail': 'Email da Empresa',
    'admin.save': 'Salvar Configurações',
    'admin.saved': 'Configurações salvas com sucesso',
    'admin.users': 'Usuários',
    'admin.deposits': 'Depósitos',
    'admin.withdrawals': 'Saques',
    'admin.kyc': 'Gerenciamento KYC',
    'admin.approveKYC': 'Aprovar KYC',
    'admin.rejectKYC': 'Rejeitar KYC',
    'admin.approveDeposit': 'Aprovar Depósito',
    'admin.rejectDeposit': 'Rejeitar Depósito',
    'admin.approveWithdrawal': 'Aprovar Saque',
    'admin.rejectWithdrawal': 'Rejeitar Saque',
    'page.termsTitle': 'Termos e Condições',
    'page.privacyTitle': 'Política de Privacidade',
    'page.aboutUs': 'Sobre Nós',
    'page.contactUs': 'Entre em Contato',
    'page.howToJoin': 'Como se Juntar',
    // Footer
    'footer.tagline': 'Seu parceiro de confiança na construção de riqueza através de investimentos inteligentes',
    'footer.contact': 'Contato',
    'footer.quickLinks': 'Links Rápidos',
    'footer.about': 'Sobre Nós',
    'footer.investmentOptions': 'Opções de Investimento',
    'footer.openAccount': 'Abrir Conta',
    'footer.login': 'Entrar',
    'footer.legal': 'Legal',
    'footer.privacyPolicy': 'Política de Privacidade',
    'footer.termsConditions': 'Termos e Condições',
    'footer.riskDisclosure': 'Divulgação de Riscos',
    'footer.compliance': 'Conformidade',
    'footer.allRights': 'Todos os direitos reservados.',
    'common.loading': 'Carregando...',
    'common.error': 'Erro',
    'common.success': 'Sucesso',
    'common.confirm': 'Confirmar',
    'common.cancel': 'Cancelar',
    'common.save': 'Salvar',
    'common.delete': 'Excluir',
    'common.edit': 'Editar',
    'common.back': 'Voltar',
    'common.next': 'Próximo',
    'common.previous': 'Anterior',
    'common.search': 'Pesquisar',
    'common.filter': 'Filtrar',
    'common.export': 'Exportar',
    'common.download': 'Baixar',
    'common.upload': 'Carregar',
    'common.language': 'Idioma',
    'common.theme': 'Tema',
    'common.currency': 'Moeda',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
